-- Comprehension questions generated after each reading session.
--
-- One question per session, generated by Claude from the book title and genre.
-- The student's answer and Claude's evaluation are stored here for teacher
-- review — a trail of "what Diego said about Charlotte's Web" is more useful
-- than a binary pass/fail.
--
-- XP is awarded regardless of the answer. The question is friction, not a gate:
-- the cost of a false positive (flagging a child who genuinely read the book
-- but expressed it poorly) outweighs the cost of a motivated cheater who looked
-- up the answer.

CREATE TABLE IF NOT EXISTS session_questions (
    id           SERIAL PRIMARY KEY,
    session_id   INT REFERENCES reading_sessions(id),
    student_id   INT REFERENCES students(id),
    book_title   TEXT NOT NULL,
    question     TEXT NOT NULL,
    answer       TEXT,                  -- null until the student responds
    evaluation   TEXT,                  -- null until Claude evaluates
    answered_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_session_questions_student
    ON session_questions (student_id, created_at DESC);
